#Benchmark config file in TOML

[BASICS]
PATH_TO_BIN = "/home/hema/UDP_socket/client"
RUNS = 1000
THREAD_COUNTING = 0
BENCHMARK_NAME="udp_socket_test"

[PARAMETERS]
NAMES = ["Server IP", "Bytes"]
SPECIFIERS = ["", ""]
VALUES = ["10.0.0.3", [144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160]]

[POST-PROCESSING]
